"""add_interview_id_to_panelist_availability

Revision ID: 0cca96e48ddd
Revises: 43eeddce4aa6
Create Date: 2026-02-28 23:41:28.928991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cca96e48ddd'
down_revision: Union[str, Sequence[str], None] = '43eeddce4aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_round_configs', sa.Column('slots_available', sa.Boolean(), nullable=False))
    op.add_column('interview_round_configs', sa.Column('candidate_slot_booking_link', sa.String(), nullable=True))
    op.add_column('panelist_availability', sa.Column('interview_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_panelist_availability_interview_id'), 'panelist_availability', ['interview_id'], unique=False)
    op.create_foreign_key(None, 'panelist_availability', 'interviews', ['interview_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'panelist_availability', type_='foreignkey')
    op.drop_index(op.f('ix_panelist_availability_interview_id'), table_name='panelist_availability')
    op.drop_column('panelist_availability', 'interview_id')
    op.drop_column('interview_round_configs', 'candidate_slot_booking_link')
    op.drop_column('interview_round_configs', 'slots_available')
    # ### end Alembic commands ###
