"""replace_calendly_with_calendar_connections

Revision ID: 10738751fd1d
Revises: f98ed7b97b41
Create Date: 2026-03-04 18:19:55.250250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10738751fd1d'
down_revision: Union[str, Sequence[str], None] = 'f98ed7b97b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('GOOGLE', 'MICROSOFT', name='calendar_provider_enum'), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('access_token', sa.TEXT(), nullable=False),
    sa.Column('refresh_token', sa.TEXT(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.TEXT(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'provider', name='uq_user_email_provider')
    )
    op.create_index(op.f('ix_calendar_connections_id'), 'calendar_connections', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_connections_user_email'), 'calendar_connections', ['user_email'], unique=False)
    op.create_index(op.f('ix_calendar_connections_user_id'), 'calendar_connections', ['user_id'], unique=False)
    op.drop_index(op.f('ix_calendly_connections_id'), table_name='calendly_connections')
    op.drop_index(op.f('ix_calendly_connections_panelist_email'), table_name='calendly_connections')
    op.drop_table('calendly_connections')
    op.add_column('panelist_availability', sa.Column('calendar_connected', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('panelist_availability', 'calendly_connected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panelist_availability', sa.Column('calendly_connected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('panelist_availability', 'calendar_connected')
    op.create_table('calendly_connections',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('panelist_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('calendly_user_uri', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('connected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('calendly_connections_pkey'))
    )
    op.create_index(op.f('ix_calendly_connections_panelist_email'), 'calendly_connections', ['panelist_email'], unique=True)
    op.create_index(op.f('ix_calendly_connections_id'), 'calendly_connections', ['id'], unique=False)
    op.drop_index(op.f('ix_calendar_connections_user_id'), table_name='calendar_connections')
    op.drop_index(op.f('ix_calendar_connections_user_email'), table_name='calendar_connections')
    op.drop_index(op.f('ix_calendar_connections_id'), table_name='calendar_connections')
    op.drop_table('calendar_connections')
    # ### end Alembic commands ###
