"""updated_interview_scheduling_tables

Revision ID: 21281581480d
Revises: b8371e7e607d
Create Date: 2026-02-26 17:50:23.428208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

ai_status_enum = postgresql.ENUM(
    "PENDING",
    "PROCESSING",
    "COMPLETED",
    "FAILED",
    name="ai_processing_status_enum"
)


# revision identifiers, used by Alembic.
revision: str = '21281581480d'
down_revision: Union[str, Sequence[str], None] = 'b8371e7e607d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendly_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('panelist_email', sa.String(), nullable=False),
    sa.Column('calendly_user_uri', sa.String(), nullable=False),
    sa.Column('access_token', sa.TEXT(), nullable=False),
    sa.Column('refresh_token', sa.TEXT(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendly_connections_id'), 'calendly_connections', ['id'], unique=False)
    op.create_index(op.f('ix_calendly_connections_panelist_email'), 'calendly_connections', ['panelist_email'], unique=True)
    op.create_table('interview_round_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('interview_type', sa.Enum('IN_PERSON', 'PHONE', 'VIDEO_CALL', name='interview_type_enum'), nullable=False),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('panelists', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meet_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'round_number', name='uq_job_round')
    )
    op.create_index(op.f('ix_interview_round_configs_id'), 'interview_round_configs', ['id'], unique=False)
    op.create_index(op.f('ix_interview_round_configs_job_id'), 'interview_round_configs', ['job_id'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('round_config_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COLLECTING_AVAILABILITY', 'READY_TO_BOOK', 'SCHEDULED', 'COMPLETED', 'CANCELED', 'IN_PROGRESS', 'AWAITING_FEEDBACK', 'FEEDBACK_COLLECTED', name='interview_status_enum'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_token', sa.TEXT(), nullable=True),
    sa.Column('booking_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['round_config_id'], ['interview_round_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_index(op.f('ix_interviews_round_config_id'), 'interviews', ['round_config_id'], unique=False)
    op.create_index(op.f('ix_interviews_round_number'), 'interviews', ['round_number'], unique=False)
    op.create_index(op.f('ix_interviews_scheduled_start'), 'interviews', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_table('interview_timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_timeline_events_event_type'), 'interview_timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_interview_timeline_events_id'), 'interview_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_interview_timeline_events_interview_id'), 'interview_timeline_events', ['interview_id'], unique=False)
    op.create_table('panelist_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('panelist_email', sa.String(), nullable=False),
    sa.Column('panelist_name', sa.String(), nullable=True),
    sa.Column('response_status', sa.Enum('SUBMITTED', 'EXPIRED', 'PENDING', name='panelist_response_status_enum'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('availability_token', sa.TEXT(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calendly_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_id', 'panelist_email', name='uq_interview_panelist')
    )
    op.create_index(op.f('ix_panelist_availability_id'), 'panelist_availability', ['id'], unique=False)
    op.create_index(op.f('ix_panelist_availability_interview_id'), 'panelist_availability', ['interview_id'], unique=False)
    op.create_index(op.f('ix_panelist_availability_panelist_email'), 'panelist_availability', ['panelist_email'], unique=False)
    # FIX: Backfill NULLs before SET NOT NULL
    op.execute("UPDATE ai_processing_logs SET ai_model = 'unknown' WHERE ai_model IS NULL")
    op.alter_column('ai_processing_logs', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # FIX: Create enum type + uppercase values before cast
    op.execute("UPDATE ai_processing_logs SET status = UPPER(status)")
    op.execute("CREATE TYPE ai_processing_status_enum AS ENUM ('PENDING', 'SUCCESS', 'FAILED')")
    op.execute("ALTER TABLE ai_processing_logs ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE ai_processing_logs ALTER COLUMN status TYPE ai_processing_status_enum USING status::ai_processing_status_enum")
    op.execute("ALTER TABLE ai_processing_logs ALTER COLUMN status SET DEFAULT 'PENDING'")
    op.drop_index(op.f('idx_ai_logs_organization'), table_name='ai_processing_logs')
    op.drop_index(op.f('idx_ai_logs_created_at'), table_name='ai_processing_logs')
    op.create_index('idx_ai_logs_created_at', 'ai_processing_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_processing_logs_organization_id'), 'ai_processing_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_processing_logs_triggered_by'), 'ai_processing_logs', ['triggered_by'], unique=False)
    op.drop_constraint(op.f('ai_processing_logs_triggered_by_fkey'), 'ai_processing_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ai_processing_logs', 'users', ['triggered_by'], ['id'], ondelete='SET NULL')
    op.alter_column('applications', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=True)
    # FIX: Backfill NULLs before SET NOT NULL
    op.execute("UPDATE applications SET updated_at = COALESCE(created_at, now()) WHERE updated_at IS NULL")
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # Removed: flag_reason TEXT→VARCHAR and tags TEXT[]→VARCHAR[] are no-ops in PostgreSQL
    # and would fail because view v_ranked_candidates depends on the tags column
    op.drop_index(op.f('idx_applications_created_at'), table_name='applications')
    op.drop_index(op.f('idx_applications_current_resume_id'), table_name='applications')
    op.drop_constraint(op.f('uq_job_candidate'), 'applications', type_='unique')
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_applications_current_resume_id'), 'applications', ['current_resume_id'], unique=False)
    op.alter_column('bulk_upload_batches', 'batch_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('bulk_upload_batches', 'source_file_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # FIX: Create enum type + uppercase values before cast
    op.execute("UPDATE bulk_upload_batches SET status = UPPER(status)")
    op.execute("CREATE TYPE bulk_upload_status_enum AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')")
    op.execute("ALTER TABLE bulk_upload_batches ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE bulk_upload_batches ALTER COLUMN status TYPE bulk_upload_status_enum USING status::bulk_upload_status_enum")
    op.execute("ALTER TABLE bulk_upload_batches ALTER COLUMN status SET DEFAULT 'PENDING'")
    op.alter_column('bulk_upload_batches', 'success_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'failed_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'scoring_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('idx_bulk_batches_job_id'), table_name='bulk_upload_batches')
    op.drop_index(op.f('idx_bulk_batches_status'), table_name='bulk_upload_batches')
    op.drop_index(op.f('idx_bulk_batches_uploaded_by'), table_name='bulk_upload_batches')
    op.create_index(op.f('ix_bulk_upload_batches_job_id'), 'bulk_upload_batches', ['job_id'], unique=False)
    op.create_index(op.f('ix_bulk_upload_batches_status'), 'bulk_upload_batches', ['status'], unique=False)
    op.create_index(op.f('ix_bulk_upload_batches_uploaded_by'), 'bulk_upload_batches', ['uploaded_by'], unique=False)
    op.drop_constraint(op.f('bulk_upload_batches_uploaded_by_fkey'), 'bulk_upload_batches', type_='foreignkey')
    op.create_foreign_key(None, 'bulk_upload_batches', 'users', ['uploaded_by'], ['id'], ondelete='RESTRICT')
    op.add_column('candidates', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    # FIX: Backfill NULLs before SET NOT NULL
    op.execute("UPDATE candidates SET updated_at = COALESCE(created_at, now()) WHERE updated_at IS NULL")
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_candidates_org_email'), table_name='candidates', postgresql_where='(email IS NOT NULL)')
    op.drop_index(op.f('idx_candidates_org_phone'), table_name='candidates', postgresql_where='(phone IS NOT NULL)')
    op.create_index(op.f('ix_candidates_created_by_user_id'), 'candidates', ['created_by_user_id'], unique=False)
    op.create_foreign_key(None, 'candidates', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('documents', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('documents', 'storage_provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'supabase'::character varying"))
    op.alter_column('documents', 'parsing_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('documents', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_constraint(op.f('documents_uploaded_by_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # FIX: Backfill NULLs before SET NOT NULL
    op.execute("UPDATE jobs SET updated_at = COALESCE(created_at, now()) WHERE updated_at IS NULL")
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_jobs_hiring_manager_id'), 'jobs', ['hiring_manager_id'], unique=False)
    op.drop_constraint(op.f('jobs_hiring_manager_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['hiring_manager_id'], ['id'], ondelete='SET NULL')
    # FIX: Rename timestamp→created_at instead of drop+add (preserves data)
    op.execute("ALTER TABLE organizations RENAME COLUMN \"timestamp\" TO created_at")
    op.execute("ALTER TABLE organizations ALTER COLUMN created_at SET DEFAULT now()")
    op.execute("UPDATE organizations SET created_at = now() WHERE created_at IS NULL")
    op.execute("ALTER TABLE organizations ALTER COLUMN created_at SET NOT NULL")
    # FIX: Backfill NULLs before SET NOT NULL
    op.execute("UPDATE organizations SET updated_at = COALESCE(created_at, now()) WHERE updated_at IS NULL")
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # FIX: Create enum type first, use UPPERCASE default
    op.execute("CREATE TYPE resume_status_enum AS ENUM ('UPLOADED', 'QUEUED_FOR_PARSING', 'PARSING_IN_PROGRESS', 'PARSED', 'QUEUED_FOR_SCORING', 'SCORING_IN_PROGRESS', 'SCORED', 'ERROR')")
    op.add_column('resumes', sa.Column('status', sa.Enum('UPLOADED', 'QUEUED_FOR_PARSING', 'PARSING_IN_PROGRESS', 'PARSED', 'QUEUED_FOR_SCORING', 'SCORING_IN_PROGRESS', 'SCORED', 'ERROR', name='resume_status_enum', create_type=False), server_default='UPLOADED', nullable=False))
    op.alter_column('resumes', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('resumes', 'raw_file_url',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('resumes', 'parsed_text',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # FIX: Backfill NULLs before SET NOT NULL
    op.execute("UPDATE resumes SET updated_at = COALESCE(uploaded_at, now()) WHERE updated_at IS NULL")
    op.alter_column('resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # FIX: Backfill NULLs before SET NOT NULL
    op.execute("UPDATE rubrics SET updated_at = COALESCE(created_at, now()) WHERE updated_at IS NULL")
    op.alter_column('rubrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rubrics', 'created_via',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('rubrics', 'change_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('rubrics', 'change_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # FIX: Backfill NULLs before SET NOT NULL
    op.execute("UPDATE scores SET updated_at = COALESCE(created_at, now()) WHERE updated_at IS NULL")
    op.alter_column('scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scores', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_scores_raw_overall_score'), table_name='scores')
    op.drop_index(op.f('idx_scores_scoring_method'), table_name='scores')
    op.create_index(op.f('ix_scores_raw_overall_score'), 'scores', ['raw_overall_score'], unique=False)
    op.create_index(op.f('ix_scores_scoring_method'), 'scores', ['scoring_method'], unique=False)
    # FIX: Backfill NULLs before SET NOT NULL
    op.execute("UPDATE users SET updated_at = COALESCE(joined_at, now()) WHERE updated_at IS NULL")
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_scores_scoring_method'), table_name='scores')
    op.drop_index(op.f('ix_scores_raw_overall_score'), table_name='scores')
    op.create_index(op.f('idx_scores_scoring_method'), 'scores', ['scoring_method'], unique=False)
    op.create_index(op.f('idx_scores_raw_overall_score'), 'scores', ['raw_overall_score'], unique=False)
    op.alter_column('scores', 'ai_model',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rubrics', 'change_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('rubrics', 'change_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('rubrics', 'created_via',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('rubrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resumes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resumes', 'parsed_text',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('resumes', 'raw_file_url',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('resumes', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('resumes', 'status')
    op.execute("DROP TYPE IF EXISTS resume_status_enum")
    # Downgrade: rename created_at back to timestamp
    op.execute("ALTER TABLE organizations RENAME COLUMN created_at TO \"timestamp\"")
    op.execute("ALTER TABLE organizations ALTER COLUMN \"timestamp\" DROP NOT NULL")
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_hiring_manager_id_fkey'), 'jobs', 'users', ['hiring_manager_id'], ['id'])
    op.drop_index(op.f('ix_jobs_hiring_manager_id'), table_name='jobs')
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_uploaded_by_fkey'), 'documents', 'users', ['uploaded_by'], ['id'])
    op.alter_column('documents', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('documents', 'parsing_status',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('documents', 'storage_provider',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'supabase'::character varying"))
    op.alter_column('documents', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_created_by_user_id'), table_name='candidates')
    op.create_index(op.f('idx_candidates_org_phone'), 'candidates', ['organization_id', 'phone'], unique=True, postgresql_where='(phone IS NOT NULL)')
    op.create_index(op.f('idx_candidates_org_email'), 'candidates', ['organization_id', 'email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('candidates', 'created_by_user_id')
    op.drop_constraint(None, 'bulk_upload_batches', type_='foreignkey')
    op.create_foreign_key(op.f('bulk_upload_batches_uploaded_by_fkey'), 'bulk_upload_batches', 'users', ['uploaded_by'], ['id'])
    op.drop_index(op.f('ix_bulk_upload_batches_uploaded_by'), table_name='bulk_upload_batches')
    op.drop_index(op.f('ix_bulk_upload_batches_status'), table_name='bulk_upload_batches')
    op.drop_index(op.f('ix_bulk_upload_batches_job_id'), table_name='bulk_upload_batches')
    op.create_index(op.f('idx_bulk_batches_uploaded_by'), 'bulk_upload_batches', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_bulk_batches_status'), 'bulk_upload_batches', ['status'], unique=False)
    op.create_index(op.f('idx_bulk_batches_job_id'), 'bulk_upload_batches', ['job_id'], unique=False)
    op.alter_column('bulk_upload_batches', 'scoring_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bulk_upload_batches', 'failed_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'success_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='bulk_upload_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.execute("UPDATE bulk_upload_batches SET status = LOWER(status)")
    op.execute("DROP TYPE IF EXISTS bulk_upload_status_enum")
    op.alter_column('bulk_upload_batches', 'source_file_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('bulk_upload_batches', 'batch_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_applications_current_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.create_unique_constraint(op.f('uq_job_candidate'), 'applications', ['job_id', 'candidate_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_applications_current_resume_id'), 'applications', ['current_resume_id'], unique=False)
    op.create_index(op.f('idx_applications_created_at'), 'applications', ['created_at'], unique=False)
    # Removed: reverse of tags/flag_reason type changes (were no-ops)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'ai_processing_logs', type_='foreignkey')
    op.create_foreign_key(op.f('ai_processing_logs_triggered_by_fkey'), 'ai_processing_logs', 'users', ['triggered_by'], ['id'])
    op.drop_index(op.f('ix_ai_processing_logs_triggered_by'), table_name='ai_processing_logs')
    op.drop_index(op.f('ix_ai_processing_logs_organization_id'), table_name='ai_processing_logs')
    op.drop_index('idx_ai_logs_created_at', table_name='ai_processing_logs')
    op.create_index(op.f('idx_ai_logs_created_at'), 'ai_processing_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_ai_logs_organization'), 'ai_processing_logs', ['organization_id'], unique=False)
    # Downgrade: revert enum to VARCHAR with lowercase
    op.execute("ALTER TABLE ai_processing_logs ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE ai_processing_logs ALTER COLUMN status TYPE VARCHAR(50) USING status::text")
    op.execute("UPDATE ai_processing_logs SET status = LOWER(status)")
    op.execute("ALTER TABLE ai_processing_logs ALTER COLUMN status SET DEFAULT 'pending'")
    op.execute("DROP TYPE IF EXISTS ai_processing_status_enum")
    op.alter_column('ai_processing_logs', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_panelist_availability_panelist_email'), table_name='panelist_availability')
    op.drop_index(op.f('ix_panelist_availability_interview_id'), table_name='panelist_availability')
    op.drop_index(op.f('ix_panelist_availability_id'), table_name='panelist_availability')
    op.drop_table('panelist_availability')
    op.drop_index(op.f('ix_interview_timeline_events_interview_id'), table_name='interview_timeline_events')
    op.drop_index(op.f('ix_interview_timeline_events_id'), table_name='interview_timeline_events')
    op.drop_index(op.f('ix_interview_timeline_events_event_type'), table_name='interview_timeline_events')
    op.drop_table('interview_timeline_events')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_scheduled_start'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_round_number'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_round_config_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_interview_round_configs_job_id'), table_name='interview_round_configs')
    op.drop_index(op.f('ix_interview_round_configs_id'), table_name='interview_round_configs')
    op.drop_table('interview_round_configs')
    op.drop_index(op.f('ix_calendly_connections_panelist_email'), table_name='calendly_connections')
    op.drop_index(op.f('ix_calendly_connections_id'), table_name='calendly_connections')
    op.drop_table('calendly_connections')
    # ### end Alembic commands ###
