"""fix_notification_enums_to_be_native

Revision ID: 33a913cf7610
Revises: b3e9a1d2c4f0
Create Date: 2026-04-19 16:18:10.085104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33a913cf7610'
down_revision: Union[str, Sequence[str], None] = 'b3e9a1d2c4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum types if they don't exist
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'entity_type_enum') THEN CREATE TYPE entity_type_enum AS ENUM ('Interview', 'Slot', 'Job'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_channel_enum') THEN CREATE TYPE notification_channel_enum AS ENUM ('ALL', 'SMS', 'EMAIL', 'IN_APP'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recipient_notification_type_enum') THEN CREATE TYPE recipient_notification_type_enum AS ENUM ('Candidate', 'Panelist', 'HR'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_status_enum') THEN CREATE TYPE notification_status_enum AS ENUM ('Pending', 'Queued', 'Completed', 'Cancelled', 'Failed'); END IF; END $$;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'entity_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('Interview', 'Slot', 'Job', name='entity_type_enum'),
               existing_nullable=False,
               postgresql_using='entity_type::entity_type_enum')
    op.alter_column('notifications', 'template_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('ALL', 'SMS', 'EMAIL', 'IN_APP', name='notification_channel_enum'),
               existing_nullable=False,
               postgresql_using='channel::notification_channel_enum')
    op.alter_column('notifications', 'recipient_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('Candidate', 'Panelist', 'HR', name='recipient_notification_type_enum'),
               existing_nullable=False,
               postgresql_using='recipient_type::recipient_notification_type_enum')
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('Pending', 'Queued', 'Completed', 'Cancelled', 'Failed', name='notification_status_enum'),
               existing_nullable=False,
               postgresql_using='status::notification_status_enum')
    op.execute("UPDATE reminders SET template_key = 'default' WHERE template_key IS NULL")

    op.alter_column('reminders', 'template_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'template_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'status',
               existing_type=sa.Enum('Pending', 'Queued', 'Completed', 'Cancelled', 'Failed', name='notification_status_enum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('notifications', 'recipient_type',
               existing_type=sa.Enum('Candidate', 'Panelist', 'HR', name='recipient_notification_type_enum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('notifications', 'channel',
               existing_type=sa.Enum('ALL', 'SMS', 'EMAIL', 'IN_APP', name='notification_channel_enum'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    op.alter_column('notifications', 'template_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'entity_type',
               existing_type=sa.Enum('Interview', 'Slot', 'Job', name='entity_type_enum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # Drop the enum types
    op.execute("DROP TYPE notification_status_enum")
    op.execute("DROP TYPE recipient_notification_type_enum")
    op.execute("DROP TYPE notification_channel_enum")
    op.execute("DROP TYPE entity_type_enum")
    # ### end Alembic commands ###
