"""added new fields in panelist and slots

Revision ID: 3b437bf2d6c6
Revises: b101879e3cf8
Create Date: 2026-03-07 21:12:19.194011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b437bf2d6c6'
down_revision: Union[str, Sequence[str], None] = 'b101879e3cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panelist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('round_config_id', sa.UUID(), nullable=False),
    sa.Column('panelist_email', sa.String(), nullable=False),
    sa.Column('panelist_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('response_status', sa.Enum('NOT_REQUESTED', 'SUBMITTED', 'EXPIRED', 'PENDING', name='panelist_response_status_enum'), nullable=False),
    sa.Column('availability_token', sa.TEXT(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rescheduling_token', sa.TEXT(), nullable=True),
    sa.Column('rescheduling_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calendar_connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['round_config_id'], ['interview_round_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_panelist_id'), 'panelist', ['id'], unique=False)
    op.create_index(op.f('ix_panelist_interview_id'), 'panelist', ['interview_id'], unique=False)
    op.create_index(op.f('ix_panelist_panelist_email'), 'panelist', ['panelist_email'], unique=False)
    op.create_index(op.f('ix_panelist_round_config_id'), 'panelist', ['round_config_id'], unique=False)
    op.drop_index(op.f('ix_panelist_availability_id'), table_name='panelist_availability')
    op.drop_index(op.f('ix_panelist_availability_interview_id'), table_name='panelist_availability')
    op.drop_index(op.f('ix_panelist_availability_panelist_email'), table_name='panelist_availability')
    op.drop_index(op.f('ix_panelist_availability_round_config_id'), table_name='panelist_availability')
    op.drop_table('panelist_availability')
    
    op.drop_constraint(op.f('uq_user_email_provider'), 'calendar_connections', type_='unique')
    op.add_column('interview_slots', sa.Column('panelist_id', sa.UUID(), nullable=True))
    op.add_column('interview_slots', sa.Column('is_expired', sa.Boolean(), nullable=False,server_default='false'))
    op.drop_index(op.f('idx_slots_available'), table_name='interview_slots', postgresql_where='(is_booked = false)')
    op.drop_index(op.f('idx_slots_booked_iv'), table_name='interview_slots', postgresql_where='(booked_interview_id IS NOT NULL)')
    op.drop_index(op.f('ix_interview_slots_panelist_email'), table_name='interview_slots')
    op.create_index(op.f('ix_interview_slots_panelist_id'), 'interview_slots', ['panelist_id'], unique=False)
    op.create_foreign_key(None, 'interview_slots', 'panelist', ['panelist_id'], ['id'], ondelete='SET NULL')
    op.drop_column('interview_slots', 'panelist_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extraction_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('interview_slots', sa.Column('panelist_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interview_slots', type_='foreignkey')
    op.drop_index(op.f('ix_interview_slots_panelist_id'), table_name='interview_slots')
    op.create_index(op.f('ix_interview_slots_panelist_email'), 'interview_slots', ['panelist_email'], unique=False)
    op.create_index(op.f('idx_slots_booked_iv'), 'interview_slots', ['booked_interview_id'], unique=False, postgresql_where='(booked_interview_id IS NOT NULL)')
    op.create_index(op.f('idx_slots_available'), 'interview_slots', ['round_config_id', 'is_booked'], unique=False, postgresql_where='(is_booked = false)')
    op.drop_column('interview_slots', 'is_expired')
    op.drop_column('interview_slots', 'panelist_id')
    op.create_unique_constraint(op.f('uq_user_email_provider'), 'calendar_connections', ['provider_email', 'provider'], postgresql_nulls_not_distinct=False)
    op.alter_column('bulk_upload_batches', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='bulk_upload_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::bulk_upload_status_enum"))
    op.create_table('panelist_availability',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('panelist_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('panelist_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response_status', postgresql.ENUM('SUBMITTED', 'EXPIRED', 'PENDING', name='panelist_response_status_enum'), autoincrement=False, nullable=False),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('available_slots', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('availability_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('round_config_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interview_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('calendar_connected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('panelist_availability_interview_id_fkey')),
    sa.ForeignKeyConstraint(['round_config_id'], ['interview_round_configs.id'], name=op.f('panelist_availability_round_config_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('panelist_availability_pkey')),
    sa.UniqueConstraint('round_config_id', 'panelist_email', name=op.f('uq_round_panelist'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_panelist_availability_round_config_id'), 'panelist_availability', ['round_config_id'], unique=False)
    op.create_index(op.f('ix_panelist_availability_panelist_email'), 'panelist_availability', ['panelist_email'], unique=False)
    op.create_index(op.f('ix_panelist_availability_interview_id'), 'panelist_availability', ['interview_id'], unique=False)
    op.create_index(op.f('ix_panelist_availability_id'), 'panelist_availability', ['id'], unique=False)
    op.drop_index(op.f('ix_panelist_round_config_id'), table_name='panelist')
    op.drop_index(op.f('ix_panelist_panelist_email'), table_name='panelist')
    op.drop_index(op.f('ix_panelist_interview_id'), table_name='panelist')
    op.drop_index(op.f('ix_panelist_id'), table_name='panelist')
    op.drop_table('panelist')
    # ### end Alembic commands ###
