"""changed foreing key from interview_id to round id in panel table

Revision ID: 43eeddce4aa6
Revises: 8f1cafa958e5
Create Date: 2026-02-28 00:13:23.310607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43eeddce4aa6'
down_revision: Union[str, Sequence[str], None] = '8f1cafa958e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panelist_availability', sa.Column('round_config_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_panelist_availability_interview_id'), table_name='panelist_availability')
    op.drop_constraint(op.f('uq_interview_panelist'), 'panelist_availability', type_='unique')
    op.create_index(op.f('ix_panelist_availability_round_config_id'), 'panelist_availability', ['round_config_id'], unique=False)
    op.create_unique_constraint('uq_round_panelist', 'panelist_availability', ['round_config_id', 'panelist_email'])
    op.drop_constraint(op.f('panelist_availability_interview_id_fkey'), 'panelist_availability', type_='foreignkey')
    op.create_foreign_key(None, 'panelist_availability', 'interview_round_configs', ['round_config_id'], ['id'])
    op.drop_column('panelist_availability', 'interview_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panelist_availability', sa.Column('interview_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'panelist_availability', type_='foreignkey')
    op.create_foreign_key(op.f('panelist_availability_interview_id_fkey'), 'panelist_availability', 'interviews', ['interview_id'], ['id'])
    op.drop_constraint('uq_round_panelist', 'panelist_availability', type_='unique')
    op.drop_index(op.f('ix_panelist_availability_round_config_id'), table_name='panelist_availability')
    op.create_unique_constraint(op.f('uq_interview_panelist'), 'panelist_availability', ['interview_id', 'panelist_email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_panelist_availability_interview_id'), 'panelist_availability', ['interview_id'], unique=False)
    op.drop_column('panelist_availability', 'round_config_id')
    # ### end Alembic commands ###
