"""added notification table

Revision ID: 57c7d38c29a7
Revises: e265d2eab470
Create Date: 2026-04-18 17:13:09.719561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57c7d38c29a7'
down_revision: Union[str, Sequence[str], None] = 'e265d2eab470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('Interview', 'Slot', 'Job', name='notifications_entity_type_enum', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('template_key', sa.String(), nullable=True),
    sa.Column('channel', sa.Enum('ALL', 'SMS', 'EMAIL', 'IN_APP', name='notification_channel_enum', native_enum=False), nullable=False),
    sa.Column('recipient_type', sa.Enum('Candidate', 'Panelist', 'HR', name='recipient_notification_type_enum', native_enum=False), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Completed', 'Cancelled', 'Failed', name='notification_status_enum', native_enum=False), nullable=False),
    sa.Column('worker_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_entity_id'), 'notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)

    # Add template_key column to reminders with nullable=True first (existing rows may be null)
    op.add_column('reminders', sa.Column('template_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_column('reminders', 'template_key')
    # ### end Alembic commands ###
