"""fix in panelist

Revision ID: 5bbe9eaae338
Revises: 6f03605d26fc
Create Date: 2026-03-07 22:12:26.973106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bbe9eaae338'
down_revision: Union[str, Sequence[str], None] = '6f03605d26fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panelist', 'availability_token',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('panelist', 'token_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('panelist', 'calendar_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
   

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panelist', 'calendar_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('panelist', 'token_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('panelist', 'availability_token',
               existing_type=sa.TEXT(),
               nullable=False)

