"""added reminder table

Revision ID: 68b58218e4f7
Revises: 59299f438cdd
Create Date: 2026-03-22 17:28:01.287834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68b58218e4f7'
down_revision: Union[str, Sequence[str], None] = '59299f438cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('Interview', 'Candidate', 'Job', name='entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('reminder_type', sa.Enum('Booking_Link', 'Interview_Upcoming', 'Feedback_Pending', 'Reschedule', name='reminder_type_enum'), nullable=False),
    sa.Column('recipient_type', sa.Enum('Candidate', 'Panelist', 'HR', name='recipient_type_enum'), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Completed', 'Cancelled', 'Failed', name='reminder_status_enum'), nullable=False),
    sa.Column('worker_job_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    # ### end Alembic commands ###
