"""fix in round_config

Revision ID: 6f03605d26fc
Revises: 3b437bf2d6c6
Create Date: 2026-03-07 21:52:09.805536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f03605d26fc'
down_revision: Union[str, Sequence[str], None] = '3b437bf2d6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_round_configs', 'panelists')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extraction_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint('uq_round_panelist', 'panelist', type_='unique')
    op.add_column('interview_round_configs', sa.Column('panelists', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
