"""added new_fields

Revision ID: b101879e3cf8
Revises: 10738751fd1d
Create Date: 2026-03-06 21:21:50.179853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b101879e3cf8'
down_revision: Union[str, Sequence[str], None] = '10738751fd1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_connections_user_email'), table_name='calendar_connections')
    op.create_index(op.f('ix_calendar_connections_provider_email'), 'calendar_connections', ['provider_email'], unique=False)
    op.create_unique_constraint('uq_provider_email_provider', 'calendar_connections', ['provider_email', 'provider'])
    op.add_column('interviews', sa.Column('meet_link', sa.TEXT(), nullable=True))
    op.add_column('interviews', sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interviews', sa.Column('transcript_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('interviews', sa.Column('calendar_event_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('interviews', sa.Column('rescheduling_token', sa.TEXT(), nullable=True))
    op.add_column('interviews', sa.Column('rescheduling_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interviews', sa.Column('times_rescheduled', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_round_panelist', 'panelist_availability', ['round_config_id', 'panelist_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extraction_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint('uq_round_panelist', 'panelist_availability', type_='unique')
    op.drop_column('interviews', 'times_rescheduled')
    op.drop_column('interviews', 'rescheduling_token_expires_at')
    op.drop_column('interviews', 'rescheduling_token')
    op.drop_column('interviews', 'calendar_event_id')
    op.drop_column('interviews', 'transcript_id')
    op.drop_column('interviews', 'summary')
    op.drop_column('interviews', 'meet_link')
    op.create_index(op.f('idx_slots_booked_iv'), 'interview_slots', ['booked_interview_id'], unique=False, postgresql_where='(booked_interview_id IS NOT NULL)')
    op.create_index(op.f('idx_slots_available'), 'interview_slots', ['round_config_id', 'is_booked'], unique=False, postgresql_where='(is_booked = false)')
    op.drop_constraint('uq_provider_email_provider', 'calendar_connections', type_='unique')
    op.drop_index(op.f('ix_calendar_connections_provider_email'), table_name='calendar_connections')
    op.create_unique_constraint(op.f('uq_user_email_provider'), 'calendar_connections', ['provider_email', 'provider'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_calendar_connections_user_email'), 'calendar_connections', ['provider_email'], unique=False)
    # ### end Alembic commands ###
