"""add created_at column

Revision ID: b8371e7e607d
Revises: 51c7bb1162bb
Create Date: 2026-02-06 23:01:12.526225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8371e7e607d'
down_revision: Union[str, Sequence[str], None] = '51c7bb1162bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_jobs_hiring_manager_id'), 'jobs', ['hiring_manager_id'], unique=False)
    op.create_foreign_key(None, 'organizations', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_hiring_manager_id'), table_name='jobs')
    op.drop_column('applications', 'created_at')
    # ### end Alembic commands ###
