"""check_missing_enums

Revision ID: c62462a9368b
Revises: 33a913cf7610
Create Date: 2026-04-19 16:41:43.387078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c62462a9368b'
down_revision: Union[str, Sequence[str], None] = '33a913cf7610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_form_configs_id'), 'application_form_configs', ['id'], unique=False)
    op.alter_column('bulk_upload_batches', 'batch_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('bulk_upload_batches', 'processed_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'scoring_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_bulk_upload_batches_job_id'), table_name='bulk_upload_batches')
    op.drop_index(op.f('ix_bulk_upload_batches_status'), table_name='bulk_upload_batches')
    op.drop_index(op.f('ix_bulk_upload_batches_uploaded_by'), table_name='bulk_upload_batches')
    op.alter_column('interview_round_configs', 'assessment_criterias',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.create_index(op.f('ix_job_descriptions_id'), 'job_descriptions', ['id'], unique=False)
    op.drop_index(op.f('idx_job_settings_ai_assessment'), table_name='job_settings')
    op.drop_index(op.f('idx_job_settings_job_id'), table_name='job_settings')
    op.drop_index(op.f('idx_job_settings_panel_reminders'), table_name='job_settings', postgresql_using='gin')
    op.drop_constraint(op.f('job_settings_job_id_key'), 'job_settings', type_='unique')
    op.create_index(op.f('ix_job_settings_job_id'), 'job_settings', ['job_id'], unique=True)
    op.drop_index(op.f('uq_jobs_public_slug'), table_name='jobs', postgresql_where='((public_slug IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_index(op.f('ix_panelist_panelist_email'), table_name='panelist')
    op.create_index(op.f('ix_panelist_email'), 'panelist', ['email'], unique=False)
    op.create_unique_constraint('uq_round_panelist', 'panelist', ['round_config_id', 'email'])
    op.drop_column('panelist', 'rescheduling_token_expires_at')
    op.drop_column('panelist', 'rescheduling_token')
    op.alter_column('scores', 'grounding_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('scores', 'breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('scores', 'scored_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'ai'::character varying"))
    op.drop_index(op.f('ix_scores_raw_overall_score'), table_name='scores')
    op.drop_index(op.f('ix_scores_scoring_method'), table_name='scores')
    op.drop_constraint(op.f('uq_app_rubric'), 'scores', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_app_rubric'), 'scores', ['application_id', 'rubric_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_scores_scoring_method'), 'scores', ['scoring_method'], unique=False)
    op.create_index(op.f('ix_scores_raw_overall_score'), 'scores', ['raw_overall_score'], unique=False)
    op.alter_column('scores', 'scored_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('scores', 'breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('scores', 'grounding_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('panelist', sa.Column('rescheduling_token', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('panelist', sa.Column('rescheduling_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('uq_round_panelist', 'panelist', type_='unique')
    op.drop_index(op.f('ix_panelist_email'), table_name='panelist')
    op.create_index(op.f('ix_panelist_panelist_email'), 'panelist', ['email'], unique=False)
    op.create_index(op.f('uq_jobs_public_slug'), 'jobs', ['public_slug'], unique=True, postgresql_where='((public_slug IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_index(op.f('ix_job_settings_job_id'), table_name='job_settings')
    op.create_unique_constraint(op.f('job_settings_job_id_key'), 'job_settings', ['job_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_job_settings_panel_reminders'), 'job_settings', ['panel_reminders'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_job_settings_job_id'), 'job_settings', ['job_id'], unique=False)
    op.create_index(op.f('idx_job_settings_ai_assessment'), 'job_settings', ['ai_assessment_enabled'], unique=False)
    op.drop_index(op.f('ix_job_descriptions_id'), table_name='job_descriptions')
    op.alter_column('interview_round_configs', 'assessment_criterias',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.create_index(op.f('ix_bulk_upload_batches_uploaded_by'), 'bulk_upload_batches', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_bulk_upload_batches_status'), 'bulk_upload_batches', ['status'], unique=False)
    op.create_index(op.f('ix_bulk_upload_batches_job_id'), 'bulk_upload_batches', ['job_id'], unique=False)
    op.alter_column('bulk_upload_batches', 'scoring_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bulk_upload_batches', 'processed_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'batch_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_application_form_configs_id'), table_name='application_form_configs')
    # ### end Alembic commands ###
