"""removed job relationship in score

Revision ID: c88eb36f1769
Revises: 7510f0934f81
Create Date: 2026-01-29 19:41:49.247977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88eb36f1769'
down_revision: Union[str, Sequence[str], None] = '7510f0934f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_job_id'), table_name='scores')
    op.drop_constraint(op.f('scores_job_id_fkey'), 'scores', type_='foreignkey')
    op.drop_column('scores', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('scores_job_id_fkey'), 'scores', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_scores_job_id'), 'scores', ['job_id'], unique=False)
    # ### end Alembic commands ###
