"""addedd assessments

Revision ID: e265d2eab470
Revises: 
Create Date: 2026-03-30 20:33:51.146403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e265d2eab470'
down_revision: Union[str, Sequence[str], None] = 'd6f8a9b1c2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('panelist_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_REQUESTED', 'REQUESTED', 'SUBMITTED', name='interview_assessment_type_enum'), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.Column('feedback_token', sa.TEXT(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['panelist_id'], ['panelist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedback_token'),
    sa.UniqueConstraint('interview_id', 'panelist_id', name='uq_interview_panelist')
    )
    op.add_column('interviews', sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interviews', sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_assessments')
    op.drop_column('interviews', 'ai_analysis')
    op.drop_column('interviews', 'ai_summary')
    # ### end Alembic commands ###
