"""alignment_check

Revision ID: f837cc2fc734
Revises: 95e8813001bc
Create Date: 2026-02-03 00:04:54.076673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f837cc2fc734'
down_revision: Union[str, Sequence[str], None] = '95e8813001bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_processing_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('ai_processing_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('ai_processing_logs', 'ai_provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ai_processing_logs', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ai_processing_logs', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='ai_processing_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('idx_ai_logs_created_at'), table_name='ai_processing_logs')
    op.drop_index(op.f('idx_ai_logs_entity'), table_name='ai_processing_logs')
    op.drop_index(op.f('idx_ai_logs_operation'), table_name='ai_processing_logs')
    op.drop_index(op.f('idx_ai_logs_organization'), table_name='ai_processing_logs')
    op.drop_index(op.f('idx_ai_logs_status'), table_name='ai_processing_logs')
    op.create_index(op.f('ix_ai_processing_logs_organization_id'), 'ai_processing_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_processing_logs_triggered_by'), 'ai_processing_logs', ['triggered_by'], unique=False)
    op.drop_constraint(op.f('ai_processing_logs_triggered_by_fkey'), 'ai_processing_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ai_processing_logs', 'users', ['triggered_by'], ['id'], ondelete='SET NULL')
    op.alter_column('applications', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('applications', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'flag_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('applications', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_job_candidate'), 'applications', type_='unique')
    op.add_column('bulk_upload_batches', sa.Column('uploaded_by_id', sa.UUID(), nullable=False))
    op.alter_column('bulk_upload_batches', 'batch_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bulk_upload_batches', 'source_file_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('bulk_upload_batches', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='bulk_upload_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bulk_upload_batches', 'processed_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'success_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'failed_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_bulk_batches_job_id'), table_name='bulk_upload_batches')
    op.drop_index(op.f('idx_bulk_batches_status'), table_name='bulk_upload_batches')
    op.drop_index(op.f('idx_bulk_batches_uploaded_by'), table_name='bulk_upload_batches')
    op.drop_constraint(op.f('bulk_upload_batches_uploaded_by_fkey'), 'bulk_upload_batches', type_='foreignkey')
    op.create_foreign_key(None, 'bulk_upload_batches', 'users', ['uploaded_by_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('bulk_upload_batches', 'uploaded_by')
    op.add_column('candidates', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_candidates_org_email'), table_name='candidates', postgresql_where='(email IS NOT NULL)')
    op.drop_index(op.f('idx_candidates_org_phone'), table_name='candidates', postgresql_where='(phone IS NOT NULL)')
    op.create_index(op.f('ix_candidates_created_by_user_id'), 'candidates', ['created_by_user_id'], unique=False)
    op.create_foreign_key(None, 'candidates', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('documents', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('documents', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('documents', 'storage_provider',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'supabase'::character varying"))
    op.alter_column('documents', 'file_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('documents', 'parsing_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('UPLOADED', 'PARSING_IN_PROGRESS', 'PARSED', 'ERROR', name='document_processing_status_enum'),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('documents', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_documents_entity'), table_name='documents')
    op.drop_index(op.f('idx_documents_is_latest'), table_name='documents')
    op.drop_index(op.f('idx_documents_parsing_status'), table_name='documents')
    op.drop_constraint(op.f('documents_uploaded_by_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.add_column('jobs', sa.Column('active_processing_queue_id', sa.UUID(), nullable=True))
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('jobs_hiring_manager_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['hiring_manager_id'], ['id'], ondelete='SET NULL')
    op.add_column('organizations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(None, 'organizations', ['created_by'])
    op.drop_column('organizations', 'timestamp')
    op.add_column('resumes', sa.Column('status', sa.Enum('UPLOADED', 'QUEUED_FOR_PARSING', 'PARSING_IN_PROGRESS', 'PARSED', 'QUEUED_FOR_SCORING', 'SCORING_IN_PROGRESS', 'SCORED', 'ERROR', name='resume_status_enum'), nullable=False))
    op.alter_column('resumes', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('resumes', 'raw_file_url',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('resumes', 'parsed_text',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('resumes', 'updated_at')
    op.alter_column('rubrics', 'threshold_score',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=False)
    op.alter_column('rubrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rubrics', 'source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MANUAL', 'AI', 'COMBINED', name='rubric_source_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('scores', 'grounding_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('scores', 'breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('scores', 'threshold_score',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=5, scale=2),
               nullable=False)
    op.alter_column('scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scores', 'scored_by',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('scores', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_app_rubric'), 'scores', type_='unique')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'created_at')
    op.create_unique_constraint(op.f('uq_app_rubric'), 'scores', ['application_id', 'rubric_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('scores', 'ai_model',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('scores', 'scored_by',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'ai'::character varying"))
    op.alter_column('scores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scores', 'threshold_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('scores', 'breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('scores', 'grounding_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('rubrics', 'source',
               existing_type=sa.Enum('MANUAL', 'AI', 'COMBINED', name='rubric_source_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('rubrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rubrics', 'threshold_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.INTEGER(),
               nullable=True)
    op.add_column('resumes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('resumes', 'parsed_text',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('resumes', 'raw_file_url',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('resumes', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('resumes', 'status')
    op.add_column('organizations', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='unique')
    op.alter_column('organizations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('organizations', 'created_at')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_hiring_manager_id_fkey'), 'jobs', 'users', ['hiring_manager_id'], ['id'])
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('jobs', 'active_processing_queue_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_uploaded_by_fkey'), 'documents', 'users', ['uploaded_by'], ['id'])
    op.create_index(op.f('idx_documents_parsing_status'), 'documents', ['parsing_status'], unique=False)
    op.create_index(op.f('idx_documents_is_latest'), 'documents', ['is_latest'], unique=False)
    op.create_index(op.f('idx_documents_entity'), 'documents', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('documents', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('documents', 'parsing_status',
               existing_type=sa.Enum('UPLOADED', 'PARSING_IN_PROGRESS', 'PARSED', 'ERROR', name='document_processing_status_enum'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('documents', 'file_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('documents', 'storage_provider',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'supabase'::character varying"))
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('documents', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('documents', 'file_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('documents', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_created_by_user_id'), table_name='candidates')
    op.create_index(op.f('idx_candidates_org_phone'), 'candidates', ['organization_id', 'phone'], unique=True, postgresql_where='(phone IS NOT NULL)')
    op.create_index(op.f('idx_candidates_org_email'), 'candidates', ['organization_id', 'email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('candidates', 'created_by_user_id')
    op.add_column('bulk_upload_batches', sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bulk_upload_batches', type_='foreignkey')
    op.create_foreign_key(op.f('bulk_upload_batches_uploaded_by_fkey'), 'bulk_upload_batches', 'users', ['uploaded_by'], ['id'])
    op.create_index(op.f('idx_bulk_batches_uploaded_by'), 'bulk_upload_batches', ['uploaded_by'], unique=False)
    op.create_index(op.f('idx_bulk_batches_status'), 'bulk_upload_batches', ['status'], unique=False)
    op.create_index(op.f('idx_bulk_batches_job_id'), 'bulk_upload_batches', ['job_id'], unique=False)
    op.alter_column('bulk_upload_batches', 'failed_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'success_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'processed_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bulk_upload_batches', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='bulk_upload_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bulk_upload_batches', 'source_file_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('bulk_upload_batches', 'batch_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('bulk_upload_batches', 'uploaded_by_id')
    op.create_unique_constraint(op.f('uq_job_candidate'), 'applications', ['job_id', 'candidate_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('applications', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('applications', 'flag_reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'current_round',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'ai_processing_logs', type_='foreignkey')
    op.create_foreign_key(op.f('ai_processing_logs_triggered_by_fkey'), 'ai_processing_logs', 'users', ['triggered_by'], ['id'])
    op.drop_index(op.f('ix_ai_processing_logs_triggered_by'), table_name='ai_processing_logs')
    op.drop_index(op.f('ix_ai_processing_logs_organization_id'), table_name='ai_processing_logs')
    op.create_index(op.f('idx_ai_logs_status'), 'ai_processing_logs', ['status'], unique=False)
    op.create_index(op.f('idx_ai_logs_organization'), 'ai_processing_logs', ['organization_id'], unique=False)
    op.create_index(op.f('idx_ai_logs_operation'), 'ai_processing_logs', ['operation_type'], unique=False)
    op.create_index(op.f('idx_ai_logs_entity'), 'ai_processing_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_ai_logs_created_at'), 'ai_processing_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('ai_processing_logs', 'status',
               existing_type=sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='ai_processing_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('ai_processing_logs', 'ai_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ai_processing_logs', 'ai_provider',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ai_processing_logs', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('ai_processing_logs', 'updated_at')
    # ### end Alembic commands ###
