"""
Rubric Generation Prompts — JD → weighted rubric JSON.

Both prompts (RUBRIC_FROM_JD_PROMPT_V2 and RUBRIC_FIXER_PROMPT) target
PipelineRubricOutput: domain, domain_confidence, threshold_score, version,
sections, and non_negotiables.
job_data is provided by the caller (user form), not generated by the LLM.
"""

from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import PromptTemplate

from src.schemas.rubric_schemas import PipelineRubricOutput


# Single parser used by both prompts — targets the actual pipeline output contract.
rubric_parser = PydanticOutputParser(pydantic_object=PipelineRubricOutput)
fixer_parser = PydanticOutputParser(pydantic_object=PipelineRubricOutput)

# Production rubric prompt: deterministic, flat importance, strict grouping
RUBRIC_FROM_JD_PROMPT_V2 = PromptTemplate(
    template="""
You are an enterprise-grade ATS rubric designer.

Your task is to generate a stable, scoring-ready rubric from a Job Description (JD) and Job Context. The rubric must support consistent resume evaluation, ranking stability, and explainable scoring.

This is a production system. Precision, structural stability, and determinism are mandatory.

CORE DESIGN PHILOSOPHY

Criteria = Scoring Dimensions
Each criterion represents a high-level measurable capability (e.g., ML Engineering Depth, Client Engagement, Cloud Deployment).

Sub-criteria = Atomic Evidence Signals
Sub-criteria represent single, atomic, resume-verifiable requirements inside a criterion.

No vague personality traits.
Do NOT include subjective or unscorable traits such as:

Passionate

Hard-working

Innovative thinker

Self-starter
Only include behaviors or skills that can be evidenced in resumes.

No duplication.
Do NOT repeat the same requirement across multiple sections.
Consolidate related requirements under one logical criterion using sub-criteria.

No hallucination.
Use ONLY information explicitly present in:

JD text

Job Context
Do NOT infer industry-standard requirements that are not written.

OUTPUT STRUCTURE

Return a JSON object with these top-level fields only:

domain (always "other")

domain_confidence (always 0.5)

threshold_score (integer, see THRESHOLD SCORE RULE below)

version (always 1)

sections (array of section objects)

non_negotiables (array of non-negotiable criterion objects — see NON-NEGOTIABLE EXTRACTION RULE below)

Each section must contain:

key (snake_case)

label (Title Case)

criteria (array)

Do NOT set section importance — it is not used in scoring and defaults to 5.

Each criterion must contain:

name (snake_case, unique within section)

display_name (Title Case)

importance (integer 1–10)

priority (integer, sequential starting at 1)

value (string or null)

value_type ("none")

sub_criteria (array; use [] if none)

Each sub_criterion must contain:

name (snake_case)

display_name (Title Case)

importance (integer 1–5)

value (string or null)

value_type ("none")

Arrays must NEVER be null. Use [].

SECTION IMPORTANCE

Sections are purely organisational groups for the UI — they have NO scoring weight.
Do NOT set section importance. It is ignored by the scoring engine and defaults to 5.
Omit it from your output entirely.

SECTION ORDER RULES

If tech role, use this section order (only include relevant ones):

required_qualifications

technical_skills

experience

tools_platforms

domain_knowledge

soft_skills

certifications

preferred_qualifications

If non-tech role:

required_qualifications

core_skills

experience

soft_skills

preferred_qualifications

Do NOT create unnecessary or empty sections.

Do NOT create sections containing only one minor criterion.
Combine logically related items when appropriate.

REQUIRED QUALIFICATIONS RULE

If JD contains explicit constraints, they MUST appear under required_qualifications:

Examples:

Years of experience (e.g., "7+ years")

Degree requirement

Location requirement

Work authorization

Clearance

Working hours / timezone

Travel %

Salary constraints (if candidate-side)

Numeric minimum experience requirements MUST appear in required_qualifications even if there is a separate experience section.

CRITERIA DESIGN RULES

Each criterion must represent a coherent, measurable capability dimension.

Do NOT create overly broad criteria mixing unrelated skills.

Do NOT create excessively narrow criteria for trivial single skills.

Use sub-criteria only when multiple atomic requirements belong under one conceptual capability.

Each sub-criterion must represent ONE atomic requirement.

Do NOT use sub-criteria for:

Binary constraints

Numeric thresholds

Standalone simple constraints

IMPORTANCE CALIBRATION

For each criterion (1–10):

10 = Explicitly mandatory / dealbreaker
8–9 = Strongly emphasized core requirement
6–7 = Important but not explicitly mandatory
4–5 = Good to have
1–3 = Minor bonus

For each sub-criterion (1–5):

5 = Most critical signal in that group
3 = Standard expectation
1 = Minor detail

CONSISTENCY RULES:

Sub-criteria importance must vary based on JD emphasis.

Do NOT assign identical importance to all sub-criteria unless JD clearly treats them equally.

PRIORITY RULE

Within each section:

Sort criteria by importance (descending)

Assign priority starting at 1

Increment by 1 without gaps

Priority must strictly reflect descending importance

VALUE FIELD RULES

Use value ONLY when an explicit strict constraint exists.

Examples:

"7+ years"

"Bachelor's in Computer Science"

"Bangalore (onsite)"

"8am–5pm EST"

"30% travel"

Value must be concise.
Do NOT include descriptive sentences.
If no strict constraint exists → set value = null.

Always set value_type = "none".

CONSTRAINT EXTRACTION RULE

Extract ALL explicit constraints:

Years of experience

Degree level

Location

Work authorization

Clearance

Travel %

Timezone / working hours

Team size (if explicitly stated)

Reporting structure (if explicitly stated)

Do NOT infer unstated constraints.

NON-NEGOTIABLE EXTRACTION RULE (CRITICAL — READ CAREFULLY)

Non-negotiables are BINARY DEALBREAKERS — if a candidate fails ANY of them, they are auto-rejected
before scoring. These are NOT scored on a 0-10 scale; they are pass/fail checks.

MAXIMUM 5 non-negotiables per rubric. Only include truly binary, verifiable dealbreakers.

Each non-negotiable object must contain:
- name (snake_case, unique)
- display_name (Title Case, human-readable)
- requirement (concise string: what is required, e.g. "Onsite in Bangalore", "7+ years ML experience")
- category (one of: "location", "work_authorization", "degree", "certification", "experience_years", "employment_type", "security_clearance", "travel", "other")
- verification_question (a binary yes/no question to verify against the resume, e.g. "Does the candidate have 7 or more years of ML/AI experience?")

WHAT TO EXTRACT AS NON-NEGOTIABLE:

Tier 1 — ALWAYS include if explicitly stated in JD:
- Location requirement (onsite/hybrid with specific city) — category: "location"
- Work authorization / visa requirement — category: "work_authorization"
- Minimum degree if explicitly stated as "required" — category: "degree"
- Professional license (CPA, PE, medical license, bar admission) — category: "certification"
- Security clearance — category: "security_clearance"

Tier 2 — Pick TOP 2-3 from JD "must have" / "required" section:
- Only select items with the STRONGEST language: "must", "required", "mandatory", "non-negotiable", "minimum"
- Prefer items with high specificity: concrete numbers ("7+ years"), certifications, tools
- Do NOT include soft skills, personality traits, or vague requirements
- Example: "7+ years ML experience" = strong non-negotiable; "strong communication skills" = NOT a non-negotiable

Tier 3 — Implicit dealbreakers (include if explicitly stated):
- Employment type (full-time only, no contractors) — category: "employment_type"
- Travel requirement ("30% travel required") — category: "travel"

WHAT TO NEVER INCLUDE AS NON-NEGOTIABLE:
- Soft skills (communication, teamwork, leadership style)
- "Nice to have" or "preferred" qualifications
- Vague requirements without measurable thresholds
- Skills that could be partially met (e.g., "Python experience" — degree matters, so it's a scored criterion)

If items are extracted as non-negotiables, they MUST NOT also appear in the required_qualifications section.
Move them OUT of sections entirely — they live only in non_negotiables.

If the JD has NO clear dealbreakers, return an empty array: non_negotiables = []

VERIFICATION QUESTION RULES:
- Must be answerable with yes/no from resume content alone
- Must be specific and unambiguous
- If evidence is absent from the resume, the answer should be "unclear" (not auto-fail)
- Example: "Does the candidate's resume indicate they are located in or willing to relocate to Bangalore?"

THRESHOLD SCORE RULE

Set threshold_score based on seniority:

Entry-level (0–3 years) → 55–60
Mid-level (3–7 years) → 60–65
Senior (7+ years) → 65–70
Leadership / managerial → 70–75

If unclear → default 60.

ANTI-HALLUCINATION RULE

Use ONLY JD text and Job Context.

Do NOT invent requirements.

Do NOT add common tools unless explicitly written.

Do NOT expand scope beyond JD.

STRICT OUTPUT RULES

Return ONLY valid JSON.

No markdown.

No explanations.

No comments.

All numeric fields must be numbers.

Arrays must never be null.

Follow OUTPUT SCHEMA exactly.

JD FORMAT HANDLING

Job descriptions come in many formats. Adapt your parsing accordingly:

- BULLET-LIST JD: Each bullet is typically one requirement. Map bullets to criteria/sub-criteria directly.
- NARRATIVE/PARAGRAPH JD: Extract individual requirements from prose. Split compound sentences into separate criteria.
- MINIMAL JD (< 5 requirements): Create fewer sections. Do NOT pad with invented requirements. A 3-criterion rubric is perfectly valid.
- STRUCTURED JD (with clear headings like "Requirements", "Preferred"): Use headings as section boundaries.

RUBRIC COMPLETENESS

Every rubric MUST cover at minimum:
- At least one skills-related section (technical_skills, core_skills, or equivalent)
- At least one experience-related criterion (years, domain experience, or equivalent)

If the JD lacks one of these entirely, create a minimal criterion with importance=3.

INPUTS

JOB DESCRIPTION
{jd_text}

JOB CONTEXT
{job_context}

OUTPUT SCHEMA (MUST MATCH)
{format_instructions}
""",
    input_variables=["jd_text", "job_context"],
    partial_variables={"format_instructions": rubric_parser.get_format_instructions()},
)


RUBRIC_FIXER_PROMPT = PromptTemplate(
    template="""
You are an ATS rubric editor.

TASK
Given a JD and an initial rubric JSON, rewrite the rubric to be cleaner and non-duplicative.

RULES (KEEP IT SIMPLE)
- Do NOT invent new requirements. Only reorganize/merge what is already present and what is explicitly supported by the JD.
- Keep differences as sub_criteria.
  Example: "Python" + "Functional programming" → one criterion like "Programming" with sub_criteria ["Python", "Functional programming"].
- Keep the rubric compact (avoid repeating the same concept in multiple criteria).
- If you merge two criteria, use the higher importance score of the two.
- Always set value_type="none". value may be a highly concise string constraint (e.g., "5+ years") or null.

NON-NEGOTIABLE RULES
- PRESERVE the non_negotiables array exactly as provided. Do NOT modify, remove, or add non-negotiable items.
- Ensure non-negotiable items do NOT appear in any section's criteria (no duplication).
- If a section criterion duplicates a non-negotiable, REMOVE the criterion from the section.

JOB DESCRIPTION
{jd_text}

INITIAL RUBRIC JSON
{rubric_json}

OUTPUT (MUST MATCH)
{format_instructions}
""",
    input_variables=["jd_text", "rubric_json"],
    partial_variables={"format_instructions": fixer_parser.get_format_instructions()},
)
